### ISSUE TITLE
Product Code Generation

### ISSUE THREAD

**Issue by djarbz** [mwmahlberg/pkv#3]
I am attempting to generate a product code from within my application so that rather than running pkv.v1 init, pkv.v1 gencode, or pkv.v1 genkey I can run the function from within my codebase and pass in the parameters.

What I would like to do is something like the following, is this possible?

err := pkv.init(generateKeyHere.key)
err := pkv.gencode(generatedKeyHere.key, checkNumber)
productKey, err := pkv.genkey(seedNumber)

**Comment by mwmahlberg** [comment]
Hello, Sir! Sorry to get back that late. I will review your request later this week.

**Comment by mwmahlberg** [comment]
Seems to be stale
